export const MSG = {
  PING: 'PING',

  // Content -> SW
  PAGE_SNAPSHOT: 'PAGE_SNAPSHOT',
  USER_ACTION: 'USER_ACTION',
  FORM_DETECTED: 'FORM_DETECTED',
  REQUEST_SCREENSHOT: 'REQUEST_SCREENSHOT',
  PAGE_TEXT: 'PAGE_TEXT',
  TEXT_SELECTED: 'TEXT_SELECTED',

  // SW -> Content
  DO_FILL: 'DO_FILL',
  HIGHLIGHT_FIELD: 'HIGHLIGHT_FIELD',
  REQUEST_SNAPSHOT: 'REQUEST_SNAPSHOT',
  EXECUTE_ACTION: 'EXECUTE_ACTION',
  REQUEST_PAGE_TEXT: 'REQUEST_PAGE_TEXT',
  SHOW_REWRITE_SUGGESTION: 'SHOW_REWRITE_SUGGESTION',

  // Sidepanel -> SW via port "ai-stream"
  AI_CHAT: 'AI_CHAT',
  AI_RECALL: 'AI_RECALL',
  AI_ABORT: 'AI_ABORT',
  AI_DESCRIBE_PAGE: 'AI_DESCRIBE_PAGE',
  AI_REWRITE: 'AI_REWRITE',

  // SW -> Sidepanel via port chunks
  STREAM_CHUNK: 'STREAM_CHUNK',
  STREAM_END: 'STREAM_END',
  STREAM_ERROR: 'STREAM_ERROR',

  // Vault CRUD
  VAULT_LIST: 'VAULT_LIST',
  VAULT_GET: 'VAULT_GET',
  VAULT_SET: 'VAULT_SET',
  VAULT_DELETE: 'VAULT_DELETE',

  // PIN / key management
  SETUP_PIN: 'SETUP_PIN',
  UNLOCK_SESSION: 'UNLOCK_SESSION',
  SESSION_STATUS: 'SESSION_STATUS',
  CHANGE_PIN: 'CHANGE_PIN',

  // Memory
  MEMORY_QUERY: 'MEMORY_QUERY',
  MEMORY_LIST: 'MEMORY_LIST',
  MEMORY_CLEAR: 'MEMORY_CLEAR',
  MEMORY_EXPORT: 'MEMORY_EXPORT',

  // Chat history
  CHAT_HISTORY: 'CHAT_HISTORY',
  CHAT_SESSION_LIST: 'CHAT_SESSION_LIST',
  CHAT_LOAD_SESSION: 'CHAT_LOAD_SESSION',

  // Settings
  SETTINGS_GET: 'SETTINGS_GET',
  SETTINGS_SET: 'SETTINGS_SET',
  MODELS_LIST: 'MODELS_LIST',

  // Form fill
  FILL_FORM: 'FILL_FORM',
  FILL_COMPLETE: 'FILL_COMPLETE',

  // Tab info
  GET_TAB_SNAPSHOT: 'GET_TAB_SNAPSHOT',

  // Endpoint probing
  PROBE_ENDPOINT: 'PROBE_ENDPOINT',

  // Screenshot
  TAKE_SCREENSHOT: 'TAKE_SCREENSHOT',

  // Stats
  GET_STATS: 'GET_STATS',
  GET_HABITS: 'GET_HABITS',

  // Calendar
  GET_CALENDAR_EVENTS: 'GET_CALENDAR_EVENTS',
  ADD_CALENDAR_EVENT: 'ADD_CALENDAR_EVENT',

  // Tab context switching
  TAB_ACTIVATED: 'TAB_ACTIVATED',

  // Content script lifecycle
  REQUEST_FRESH_SNAPSHOT: 'REQUEST_FRESH_SNAPSHOT',
  GET_PAGE_STATE: 'GET_PAGE_STATE',
} as const

export type MsgType = (typeof MSG)[keyof typeof MSG]

export const DB_NAME = 'pwa_memory'
export const DB_VERSION = 2

export const STORE = {
  CHAT_HISTORY: 'chat_history',
  SESSION_MEMORY: 'session_memory',
  GLOBAL_MEMORY: 'global_memory',
  VAULT: 'vault',
  SETTINGS: 'settings',
  CALENDAR_EVENTS: 'calendar_events',
  HABIT_PATTERNS: 'habit_patterns',
} as const

export const PORT_AI_STREAM = 'ai-stream'

export const DEFAULTS = {
  LM_STUDIO_URL: '',
  LM_STUDIO_MODEL: '',
  AUTH_TOKEN: '',
  RATE_LIMIT_RPM: 10,
  MONITORING_ENABLED: true,
  VISION_ENABLED: false,
  MAX_CONTEXT_MESSAGES: 20,
  BG_SUMMARIZE_INTERVAL_MINUTES: 5,
  ACTION_FLUSH_INTERVAL_MS: 30_000,
  ACTION_BUFFER_SIZE: 500,
  SCREENSHOT_INTERVAL_SEC: 10,
  TEXT_REWRITE_ENABLED: true,
  CALENDAR_DETECTION_ENABLED: true,
  ONBOARDING_COMPLETE: false,
} as const

export const SESSION_KEY_STORAGE = 'sessionKey'
export const TOKEN_BUCKET_STORAGE = 'tokenBucket'
