export const MSG = {
  PING: 'PING',

  // Content -> SW
  PAGE_SNAPSHOT: 'PAGE_SNAPSHOT',
  USER_ACTION: 'USER_ACTION',
  FORM_DETECTED: 'FORM_DETECTED',
  REQUEST_SCREENSHOT: 'REQUEST_SCREENSHOT',
  PAGE_TEXT: 'PAGE_TEXT',
  TEXT_SELECTED: 'TEXT_SELECTED',
  /** Ask service worker to flush buffered user actions to memory + learning (content script periodic). */
  FLUSH_ACTION_BUFFER: 'FLUSH_ACTION_BUFFER',

  // SW -> Content
  DO_FILL: 'DO_FILL',
  HIGHLIGHT_FIELD: 'HIGHLIGHT_FIELD',
  REQUEST_SNAPSHOT: 'REQUEST_SNAPSHOT',
  EXECUTE_ACTION: 'EXECUTE_ACTION',
  REQUEST_PAGE_TEXT: 'REQUEST_PAGE_TEXT',
  SHOW_REWRITE_SUGGESTION: 'SHOW_REWRITE_SUGGESTION',

  // Sidepanel -> SW via port "ai-stream"
  AI_CHAT: 'AI_CHAT',
  AI_RECALL: 'AI_RECALL',
  AI_ABORT: 'AI_ABORT',
  AI_DESCRIBE_PAGE: 'AI_DESCRIBE_PAGE',
  AI_REWRITE: 'AI_REWRITE',
  AI_MEMORY_SEARCH: 'AI_MEMORY_SEARCH',

  // SW -> Sidepanel via port chunks
  MEMORY_SEARCH_CONTEXT: 'MEMORY_SEARCH_CONTEXT',
  STREAM_CHUNK: 'STREAM_CHUNK',
  STREAM_END: 'STREAM_END',
  STREAM_ERROR: 'STREAM_ERROR',

  // Vault CRUD
  VAULT_LIST: 'VAULT_LIST',
  VAULT_GET: 'VAULT_GET',
  VAULT_SET: 'VAULT_SET',
  VAULT_DELETE: 'VAULT_DELETE',

  // PIN / key management
  SETUP_PIN: 'SETUP_PIN',
  UNLOCK_SESSION: 'UNLOCK_SESSION',
  SESSION_STATUS: 'SESSION_STATUS',
  CHANGE_PIN: 'CHANGE_PIN',

  // Memory
  MEMORY_QUERY: 'MEMORY_QUERY',
  MEMORY_LIST: 'MEMORY_LIST',
  MEMORY_CLEAR: 'MEMORY_CLEAR',
  MEMORY_EXPORT: 'MEMORY_EXPORT',
  FULL_BACKUP: 'FULL_BACKUP',
  FULL_RESTORE: 'FULL_RESTORE',

  // Chat history
  CHAT_HISTORY: 'CHAT_HISTORY',
  CHAT_SESSION_LIST: 'CHAT_SESSION_LIST',
  CHAT_LOAD_SESSION: 'CHAT_LOAD_SESSION',

  // Settings
  SETTINGS_GET: 'SETTINGS_GET',
  SETTINGS_SET: 'SETTINGS_SET',
  MODELS_LIST: 'MODELS_LIST',

  // Form fill
  FILL_FORM: 'FILL_FORM',
  FILL_COMPLETE: 'FILL_COMPLETE',

  // Tab info
  GET_TAB_SNAPSHOT: 'GET_TAB_SNAPSHOT',

  // Endpoint probing
  PROBE_ENDPOINT: 'PROBE_ENDPOINT',
  AI_HEALTH_CHECK: 'AI_HEALTH_CHECK',

  // Screenshot
  TAKE_SCREENSHOT: 'TAKE_SCREENSHOT',

  // Stats
  GET_STATS: 'GET_STATS',
  GET_HABITS: 'GET_HABITS',

  // Calendar
  GET_CALENDAR_EVENTS: 'GET_CALENDAR_EVENTS',
  ADD_CALENDAR_EVENT: 'ADD_CALENDAR_EVENT',

  // Tab context switching
  TAB_ACTIVATED: 'TAB_ACTIVATED',

  // Content script lifecycle
  REQUEST_FRESH_SNAPSHOT: 'REQUEST_FRESH_SNAPSHOT',
  GET_PAGE_STATE: 'GET_PAGE_STATE',

  // Session management
  RESOLVE_SESSION: 'RESOLVE_SESSION',
  CLEAR_SESSION: 'CLEAR_SESSION',
  COMPACT_CONTEXT: 'COMPACT_CONTEXT',
  GLOBAL_SEARCH: 'GLOBAL_SEARCH',

  // Activity indicator + stop automation
  SHOW_ACTIVITY_BORDER: 'SHOW_ACTIVITY_BORDER',
  HIDE_ACTIVITY_BORDER: 'HIDE_ACTIVITY_BORDER',
  STOP_AUTOMATION: 'STOP_AUTOMATION',

  // Form Coach — step-by-step guided form filling
  FORM_COACH_START: 'FORM_COACH_START',
  FORM_COACH_DONE: 'FORM_COACH_DONE',

  // Guided Mode — highlight-and-wait for user click
  GUIDED_HIGHLIGHT: 'GUIDED_HIGHLIGHT',
  GUIDED_HIDE: 'GUIDED_HIDE',

  // Element markers / accessibility tree
  INJECT_MARKERS: 'INJECT_MARKERS',
  REMOVE_MARKERS: 'REMOVE_MARKERS',
  CLICK_MARKER: 'CLICK_MARKER',
  EXECUTE_BY_AI_ID: 'EXECUTE_BY_AI_ID',
  READ_PAGE: 'READ_PAGE',

  ANALYZE_FILE: 'ANALYZE_FILE',

  // Debug / error log
  GET_DEBUG_INFO: 'GET_DEBUG_INFO',
  CLEAR_ERRORS: 'CLEAR_ERRORS',

  // Clipboard
  CLIP_RECORD: 'CLIP_RECORD',
  CLIP_SEARCH: 'CLIP_SEARCH',
  CLIP_RECENT: 'CLIP_RECENT',
  CLIP_CLEAR: 'CLIP_CLEAR',

  // Workflows
  WORKFLOW_CREATE: 'WORKFLOW_CREATE',
  WORKFLOW_START: 'WORKFLOW_START',
  WORKFLOW_PAUSE: 'WORKFLOW_PAUSE',
  WORKFLOW_RESUME: 'WORKFLOW_RESUME',
  WORKFLOW_CANCEL: 'WORKFLOW_CANCEL',
  WORKFLOW_PROGRESS: 'WORKFLOW_PROGRESS',
  WORKFLOW_LIST: 'WORKFLOW_LIST',

  // Command Palette
  COMMAND_PALETTE_SEARCH: 'COMMAND_PALETTE_SEARCH',
  COMMAND_PALETTE_EXECUTE: 'COMMAND_PALETTE_EXECUTE',
  TOGGLE_COMMAND_PALETTE: 'TOGGLE_COMMAND_PALETTE',

  SET_SAFETY_BORDER: 'SET_SAFETY_BORDER',
  REQUEST_COMPOSE_REWRITE: 'REQUEST_COMPOSE_REWRITE',

  // Confirmation flow
  CONFIRM_ACTION: 'CONFIRM_ACTION',
  CONFIRM_RESPONSE: 'CONFIRM_RESPONSE',

  // Mode choice — ask user to pick Auto or Guided before executing actions
  MODE_CHOICE: 'MODE_CHOICE',
  MODE_CHOICE_RESPONSE: 'MODE_CHOICE_RESPONSE',

  // Page analysis
  ANALYZE_PAGE: 'ANALYZE_PAGE',

  /** Test local MemPalace bridge (GET /health). */
  MEMPALACE_PROBE: 'MEMPALACE_PROBE',
  /** Append recent session memory lines to bridge JSONL inbox for mining. */
  MEMPALACE_PUSH_INBOX: 'MEMPALACE_PUSH_INBOX',

  LEARNING_START: 'LEARNING_START',
  LEARNING_STOP: 'LEARNING_STOP',
  LEARNING_STATUS: 'LEARNING_STATUS',
  GEMINI_MODELS: 'GEMINI_MODELS',

  SUPERVISED_START: 'SUPERVISED_START',
  SUPERVISED_STOP: 'SUPERVISED_STOP',
  SUPERVISED_STATUS: 'SUPERVISED_STATUS',
  SUPERVISED_VOICE_SEGMENT: 'SUPERVISED_VOICE_SEGMENT',
  SUPERVISED_COMMAND_DONE: 'SUPERVISED_COMMAND_DONE',
  PLAYBOOK_MATCH: 'PLAYBOOK_MATCH',
  PLAYBOOK_LIST: 'PLAYBOOK_LIST',
  PLAYBOOK_DELETE: 'PLAYBOOK_DELETE',
  SHOW_CLICK_EFFECT: 'SHOW_CLICK_EFFECT',

  // Offscreen STT relay
  STT_OFFSCREEN_START: 'STT_OFFSCREEN_START',
  STT_OFFSCREEN_STOP: 'STT_OFFSCREEN_STOP',
  STT_OFFSCREEN_READY: 'STT_OFFSCREEN_READY',
  STT_TRANSCRIPT_RELAY: 'STT_TRANSCRIPT_RELAY',
  STT_COMMAND_RELAY: 'STT_COMMAND_RELAY',
  STT_ERROR_RELAY: 'STT_ERROR_RELAY',
  STT_STATUS_RELAY: 'STT_STATUS_RELAY',
  STT_START_VIA_OFFSCREEN: 'STT_START_VIA_OFFSCREEN',
  STT_STOP_VIA_OFFSCREEN: 'STT_STOP_VIA_OFFSCREEN',
  MIC_PERMISSION_RESULT: 'MIC_PERMISSION_RESULT',
} as const

export type MsgType = (typeof MSG)[keyof typeof MSG]

export const DB_NAME = 'pwa_memory'
export const DB_VERSION = 9

export const STORE = {
  CHAT_HISTORY: 'chat_history',
  SESSION_MEMORY: 'session_memory',
  GLOBAL_MEMORY: 'global_memory',
  VAULT: 'vault',
  SETTINGS: 'settings',
  CALENDAR_EVENTS: 'calendar_events',
  HABIT_PATTERNS: 'habit_patterns',
  DOMAIN_SKILLS: 'domain_skills',
  USER_BEHAVIORS: 'user_behaviors',
  LEARNING_SESSIONS: 'learning_sessions',
  SUPERVISED_PLAYBOOKS: 'supervised_playbooks',
  SUPERVISED_SESSIONS: 'supervised_sessions',
  VISUAL_SITEMAP: 'visual_sitemap',
  LOCAL_MEMORY: 'local_memory',
  INPUT_JOURNAL: 'input_journal',
} as const

export const PORT_AI_STREAM = 'ai-stream'
export const PORT_STT_RELAY = 'stt-relay'

/** chrome.storage.session key: mic granted (timestamp ms), fast sync across contexts this session. */
export const SESSION_MIC_PERMISSION_KEY = 'stt_mic_permission_ts'

/** chrome.storage.local key: persistent mic grant timestamp (survives browser restart). */
export const LOCAL_MIC_PERMISSION_KEY = 'stt_mic_permission_granted_at'

export const DEFAULTS = {
  ACTIVE_PROVIDER: 'local' as const,
  LM_STUDIO_URL: 'http://localhost:1234/v1',
  LM_STUDIO_MODEL: '',
  AUTH_TOKEN: '',
  RATE_LIMIT_RPM: 10,
  MONITORING_ENABLED: true,
  VISION_ENABLED: false,
  MAX_CONTEXT_MESSAGES: 20,
  BG_SUMMARIZE_INTERVAL_MINUTES: 5,
  ACTION_FLUSH_INTERVAL_MS: 30_000,
  ACTION_BUFFER_SIZE: 500,
  SCREENSHOT_INTERVAL_SEC: 10,
  TEXT_REWRITE_ENABLED: true,
  MEMPALACE_BRIDGE_ENABLED: false,
  MEMPALACE_BRIDGE_URL: 'http://127.0.0.1:8765',
  LOCAL_MEMORY_ENABLED: true,
  LOCAL_MEMORY_MAX_ENTRIES: 500,
  AUTO_COLLECT_ENABLED: true,
  AUTO_COLLECT_MIN_FIELDS: 3,
  CALENDAR_DETECTION_ENABLED: true,
  ONBOARDING_COMPLETE: false,
  SAFETY_BORDER_ENABLED: false,
  COMPOSE_ASSISTANT_ENABLED: true,
  AI_ACTION_LEARNING_ENABLED: true,
  LEARNING_MODE_ACTIVE: false,
  LEARNING_SNAPSHOT_INTERVAL_SEC: 3,
  STT_PROVIDER: 'web-speech' as const,
  WHISPER_ENDPOINT: '',
  CONTEXT_WINDOW_TOKENS: 0,
  LITE_MODE: false,
  TELEGRAM_BOT_ENABLED: false,
  TELEGRAM_POLL_INTERVAL_SEC: 5,
  AUTOMATION_PREFERENCE: 'ask' as const,
  INPUT_JOURNAL_ENABLED: true,
  VAULT_LOCK_TIMEOUT_MIN: 15,
  THEME: 'dark' as const,
} as const

export const SESSION_KEY_STORAGE = 'sessionKey'
export const TOKEN_BUCKET_STORAGE = 'tokenBucket'
